const projects = [
    {
      title: "Corporate Website Redesign",
      provider: "Pixel Perfect Inc.",
      providerLink: "#",
      status: "In Progress",
      progress: 10,
      badgeColor: "orange",
      badgeBg: "orange.100",
    },
    {
      title: "Mobile App UI/UX",
      provider: "Creative Solutions",
      providerLink: "#",
      status: "Awaiting Approval",
      progress: 50,
      badgeColor: "orange.600",
      badgeBg: "yellow.100",
    },
    {
      title: "Brand Logo Design",
      provider: "Artisan Graphics",
      providerLink: "#",
      status: "Completed",
      progress: 100,
      badgeColor: "green.600",
      badgeBg: "green.100",
    },
    {
      title: "Social Media Campaign",
      provider: "Buzz Marketing",
      providerLink: "#",
      status: "In Progress",
      progress: 40,
      badgeColor: "blue.600",
      badgeBg: "blue.100",
    },
    {
      title: "eCommerce Platform",
      provider: "ShopNow Inc.",
      providerLink: "#",
      status: "Planning",
      progress: 10,
      badgeColor: "gray.600",
      badgeBg: "gray.100",
    },
    {
      title: "3D Product Animation",
      provider: "Motion Studio",
      providerLink: "#",
      status: "In Progress",
      progress: 55,
      badgeColor: "purple.600",
      badgeBg: "purple.100",
    },
    {
      title: "User Research",
      provider: "InsightLab",
      providerLink: "#",
      status: "Completed",
      progress: 100,
      badgeColor: "green.600",
      badgeBg: "green.100",
    },
    {
      title: "Onboarding Flow",
      provider: "UX Pro Inc.",
      providerLink: "#",
      status: "In Progress",
      progress: 70,
      badgeColor: "orange",
      badgeBg: "orange.100",
    },
    {
      title: "Email Campaign",
      provider: "MailBlaster",
      providerLink: "#",
      status: "Awaiting Approval",
      progress: 85,
      badgeColor: "yellow.600",
      badgeBg: "yellow.100",
    },
    {
      title: "Customer Feedback Tool",
      provider: "ListenUp",
      providerLink: "#",
      status: "In Progress",
      progress: 35,
      badgeColor: "blue.600",
      badgeBg: "blue.100",
    },
    {
      title: "Data Dashboard",
      provider: "DataViz Co.",
      providerLink: "#",
      status: "In Progress",
      progress: 50,
      badgeColor: "cyan.600",
      badgeBg: "cyan.100",
    },
    {
      title: "Tutorial Video Series",
      provider: "Learnly",
      providerLink: "#",
      status: "Completed",
      progress: 100,
      badgeColor: "green.600",
      badgeBg: "green.100",
    },
  ];
  
  export default projects;
  