export const servicesData = {
  tech: [
    {
      id: 1,
      category: "tech",
      subcategory: "web-dev",
      title: "Full-Stack Web Development",
      provider: "John Smith",
      pricePerTask: 150000,
      pricePerHour: 20000,
      rating: 4.9,
      reviews: 120,
      deliveries: 85,
      languages: ["English", "Spanish"],
      location: "Lagos, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 14,
      image: "https://placehold.co/600x400/3B82F6/FFFFFF?text=Web+Dev",
    },
    {
      id: 2,
      category: "tech",
      subcategory: "mobile-dev",
      title: "React Native Mobile App Development",
      provider: "Jane Doe",
      pricePerTask: 250000,
      pricePerHour: 30000,
      rating: 5.0,
      reviews: 95,
      deliveries: 70,
      languages: ["English"],
      location: "Abuja, Nigeria",
      availability: "Busy (1 week)",
      avgDeliveryTime: 21,
      image: "https://placehold.co/600x400/10B981/FFFFFF?text=Mobile+App",
    },
    {
      id: 3,
      category: "tech",
      subcategory: "cybersecurity",
      title: "Cybersecurity Audit & Pen Testing",
      provider: "SecureTech Labs",
      pricePerTask: 300000,
      pricePerHour: 45000,
      rating: 4.8,
      reviews: 60,
      deliveries: 40,
      languages: ["English", "French"],
      location: "Cape Town, South Africa",
      availability: "Available Now",
      avgDeliveryTime: 10,
      image: "https://placehold.co/600x400/1E293B/FFFFFF?text=Cybersecurity",
    },
    {
      id: 4,
      category: "tech",
      subcategory: "data-science",
      title: "Data Analysis & Visualization",
      provider: "Data Insights Pro",
      pricePerTask: 180000,
      pricePerHour: 25000,
      rating: 4.7,
      reviews: 45,
      deliveries: 32,
      languages: ["English"],
      location: "Nairobi, Kenya",
      availability: "Available in 2 days",
      avgDeliveryTime: 7,
      image: "https://placehold.co/600x400/0EA5E9/FFFFFF?text=Data+Science",
    },

    {
      id: 19,
      category: "tech",
      subcategory: "cloud-services",
      title: "Cloud Infrastructure Setup & Management",
      provider: "CloudMasters",
      pricePerTask: 220000,
      pricePerHour: 35000,
      rating: 4.9,
      reviews: 80,
      deliveries: 60,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 5,
      image: "https://placehold.co/600x400/6366F1/FFFFFF?text=Cloud+Services",
    },
    {
      id: 20,
      category: "tech",
      subcategory: "ai-development",
      title: "AI Model Development & Integration",
      provider: "AI Innovators",
      pricePerTask: 350000,
      pricePerHour: 50000,
      rating: 5.0,
      reviews: 100,
      deliveries: 80,
      languages: ["English", "French"],
      location: "Online",
      availability: "Busy (1 week)",
      avgDeliveryTime: 14,
      image: "https://placehold.co/600x400/8B5CF6/FFFFFF?text=AI+Development",
    },
    {
      id: 21,
      category: "tech",
      subcategory: "blockchain",
      title: "Blockchain Development & Smart Contracts",
      provider: "BlockTech Solutions",
      pricePerTask: 400000,
      pricePerHour: 60000,
      rating: 4.8,
      reviews: 70,
      deliveries: 50,
      languages: ["English", "Spanish"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 10,
      image: "https://placehold.co/600x400/2563EB/FFFFFF?text=Blockchain+Dev",
    },
  ],

  creative: [
    {
      id: 5,
      category: "creative",
      subcategory: "graphic-design",
      title: "Modern Logo Design & Branding",
      provider: "Emily White",
      pricePerTask: 30000,
      pricePerHour: 5000,
      rating: 4.8,
      reviews: 250,
      deliveries: 200,
      languages: ["English"],
      location: "Accra, Ghana",
      availability: "Available Now",
      avgDeliveryTime: 5,
      image: "https://placehold.co/600x400/F59E0B/FFFFFF?text=Logo+Design",
    },
    {
      id: 6,
      category: "creative",
      subcategory: "video-editing",
      title: "Professional Video Editing for Social Media",
      provider: "Visual Storytellers",
      pricePerTask: 75000,
      pricePerHour: 12000,
      rating: 4.9,
      reviews: 180,
      deliveries: 150,
      languages: ["English", "French"],
      location: "Lagos, Nigeria",
      availability: "Busy (3 days)",
      avgDeliveryTime: 7,
      image: "https://placehold.co/600x400/EF4444/FFFFFF?text=Video+Edit",
    },
    {
      id: 7,
      category: "creative",
      subcategory: "illustration",
      title: "Custom Digital Illustrations",
      provider: "Artify Studio",
      pricePerTask: 40000,
      pricePerHour: 6000,
      rating: 5.0,
      reviews: 90,
      deliveries: 85,
      languages: ["English", "Spanish"],
      location: "Johannesburg, South Africa",
      availability: "Available Now",
      avgDeliveryTime: 4,
      image: "https://placehold.co/600x400/FB923C/FFFFFF?text=Illustration",
    },
  ],

  business: [
    {
      id: 8,
      category: "business",
      subcategory: "digital-marketing",
      title: "SEO & Digital Marketing Specialist",
      provider: "Michael Brown",
      pricePerTask: 80000,
      pricePerHour: 15000,
      rating: 4.9,
      reviews: 150,
      deliveries: 110,
      languages: ["English"],
      location: "Nairobi, Kenya",
      availability: "Available Now",
      avgDeliveryTime: 10,
      image: "https://placehold.co/600x400/8B5CF6/FFFFFF?text=Marketing",
    },
    {
      id: 9,
      category: "business",
      subcategory: "strategy-consulting",
      title: "Business Plan & Growth Strategy",
      provider: "Strategic Advisors",
      pricePerTask: 120000,
      pricePerHour: 20000,
      rating: 4.6,
      reviews: 60,
      deliveries: 45,
      languages: ["English"],
      location: "Lagos, Nigeria",
      availability: "Busy (5 days)",
      avgDeliveryTime: 14,
      image: "https://placehold.co/600x400/06B6D4/FFFFFF?text=Biz+Plan",
    },
    {
      id: 10,
      category: "business",
      subcategory: "legal-services",
      title: "Business Contract Drafting & Review",
      provider: "LawPro Consult",
      pricePerTask: 60000,
      pricePerHour: 12000,
      rating: 4.8,
      reviews: 40,
      deliveries: 35,
      languages: ["English"],
      location: "Abuja, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 3,
      image: "https://placehold.co/600x400/4C1D95/FFFFFF?text=Legal",
    },
    {
      id: 25,
      category: "business",
      subcategory: "financial-advisory",
      title: "Financial Planning & Investment Advice",
      provider: "Finance Gurus",
      pricePerTask: 100000,
      pricePerHour: 18000,
      rating: 4.9,
      reviews: 75,
      deliveries: 60,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 2,
      image: "https://placehold.co/600x400/10B981/FFFFFF?text=Finance+Advisory",
    },
    {
      id: 26,
      category: "business",
      subcategory: "human-resources",
      title: "HR Consulting & Recruitment Services",
      provider: "Talent Solutions",
      pricePerTask: 90000,
      pricePerHour: 15000,
      rating: 4.8,
      reviews: 50,
      deliveries: 40,
      languages: ["English"],
      location: "Online",
      availability: "Busy (1 week)",
      avgDeliveryTime: 7,
      image: "https://placehold.co/600x400/EF4444/FFFFFF?text=HR+Consulting",
    },
    {
      id: 27,
      category: "business",
      subcategory: "project-management",
      title: "Project Management & Coordination",
      provider: "PM Experts Ltd",
      pricePerTask: 110000,
      pricePerHour: 20000,
      rating: 4.7,
      reviews: 65,
      deliveries: 55,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 3,
      image: "https://placehold.co/600x400/2563EB/FFFFFF?text=Project+Management",
    },
    {
      id: 28,
      category: "business",
      subcategory: "supply-chain",
      title: "Supply Chain Management & Logistics",
      provider: "LogiMasters",
      pricePerTask: 130000,
      pricePerHour: 22000,
      rating: 4.8,
      reviews: 55,
      deliveries: 45,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 4,
      image: "https://placehold.co/600x400/22C55E/FFFFFF?text=Supply+Chain",
    },
    {
      id: 29,
      category: "business",
      subcategory: "market-research",
      title: "Market Research & Analysis",
      provider: "Insight Analysts",
      pricePerTask: 85000,
      pricePerHour: 15000,
      rating: 4.9,
      reviews: 70,
      deliveries: 60,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 3,
      image: "https://placehold.co/600x400/8B5CF6/FFFFFF?text=Market+Research",
    },
    {
      id: 30,
      category: "business",
      subcategory: "branding",
      title: "Brand Strategy & Identity Development",
      provider: "Brand Builders",
      pricePerTask: 95000,
      pricePerHour: 17000,
      rating: 4.8,
      reviews: 80,
      deliveries: 70,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 5,
      image: "https://placehold.co/600x400/2563EB/FFFFFF?text=Branding",
    },
  ],

  trades: [
    {
      id: 11,
      category: "trades",
      subcategory: "carpentry",
      title: "Custom Wood Furniture & Repairs",
      provider: "WoodCraft Pro",
      pricePerTask: 90000,
      pricePerHour: 15000,
      rating: 4.9,
      reviews: 30,
      deliveries: 25,
      languages: ["English"],
      location: "Ibadan, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 20,
      image: "https://placehold.co/600x400/A0522D/FFFFFF?text=Carpentry",
    },
    {
      id: 12,
      category: "trades",
      subcategory: "mechanics",
      title: "Motor Vehicle Diagnostics & Repairs",
      provider: "AutoFix Experts",
      pricePerTask: 25000,
      pricePerHour: 5000,
      rating: 4.7,
      reviews: 110,
      deliveries: 100,
      languages: ["English", "Yoruba"],
      location: "Abeokuta, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 2,
      image: "https://placehold.co/600x400/607D8B/FFFFFF?text=Mechanic",
    },
    {
      id: 13,
      category: "trades",
      subcategory: "plumbing",
      title: "Residential & Commercial Plumbing",
      provider: "PipeMasters Ltd",
      pricePerTask: 40000,
      pricePerHour: 7000,
      rating: 4.8,
      reviews: 50,
      deliveries: 45,
      languages: ["English"],
      location: "Port Harcourt, Nigeria",
      availability: "Busy (2 days)",
      avgDeliveryTime: 3,
      image: "https://placehold.co/600x400/2563EB/FFFFFF?text=Plumbing",
    },
  ],

  culinary: [
    {
      id: 14,
      category: "culinary",
      subcategory: "baking",
      title: "Custom Celebration Cakes",
      provider: "Sweet Delights",
      pricePerTask: 40000,
      pricePerHour: 5000,
      rating: 5.0,
      reviews: 150,
      deliveries: 130,
      languages: ["English"],
      location: "Lagos, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 3,
      image: "https://placehold.co/600x400/FFC0CB/000000?text=Baking",
    },
    {
      id: 15,
      category: "culinary",
      subcategory: "catering",
      title: "Event Catering Services",
      provider: "Gourmet Bites",
      pricePerTask: 200000,
      pricePerHour: 35000,
      rating: 4.8,
      reviews: 80,
      deliveries: 60,
      languages: ["English"],
      location: "Abuja, Nigeria",
      availability: "Busy (1 week)",
      avgDeliveryTime: 7,
      image: "https://placehold.co/600x400/8B0000/FFFFFF?text=Catering",
    },
    {
      id: 22,
      category: "culinary",
      subcategory: "meal-prep",
      title: "Healthy Meal Prep Services",
      provider: "FitMeals Co.",
      pricePerTask: 15000,
      pricePerHour: 3000,
      rating: 4.9,
      reviews: 90,
      deliveries: 75,
      languages: ["English"],
      location: "Online (Delivery Available)",
      availability: "Available Now",
      avgDeliveryTime: 1,
      image: "https://placehold.co/600x400/32CD32/FFFFFF?text=Meal+Prep",
    },
    {
      id: 23,
      category: "culinary",
      subcategory: "cooking-classes",
      title: "Online Cooking Classes",
      provider: "Chef Academy",
      pricePerTask: 20000,
      pricePerHour: 4000,
      rating: 4.7,
      reviews: 65,
      deliveries: 50,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 0, // Instant access
      image: "https://placehold.co/600x400/FFA500/FFFFFF?text=Cooking+Classes",
    },
    {
      id: 24,
      category: "culinary",
      subcategory: "private-chef",
      title: "Private Chef Services",
      provider: "Elite Chefs",
      pricePerTask: 80000,
      pricePerHour: 15000,
      rating: 4.9,
      reviews: 110,
      deliveries: 90,
      languages: ["English"],
      location: "Lagos, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 2,
      image: "https://placehold.co/600x400/FFD700/FFFFFF?text=Private+Chef",
    },
  ],

  education: [
    {
      id: 16,
      category: "education",
      subcategory: "tutoring",
      title: "Math & Science Tutoring",
      provider: "Bright Minds Tutors",
      pricePerTask: 10000,
      pricePerHour: 2000,
      rating: 4.9,
      reviews: 70,
      deliveries: 65,
      languages: ["English"],
      location: "Lagos, Nigeria",
      availability: "Available Now",
      avgDeliveryTime: 1,
      image: "https://placehold.co/600x400/4CAF50/FFFFFF?text=Tutoring",
    },
    {
      id: 17,
      category: "education",
      subcategory: "language-lessons",
      title: "French Language Lessons",
      provider: "LanguePro",
      pricePerTask: 15000,
      pricePerHour: 3000,
      rating: 4.8,
      reviews: 55,
      deliveries: 50,
      languages: ["English", "French"],
      location: "Dakar, Senegal",
      availability: "Available Now",
      avgDeliveryTime: 2,
      image: "https://placehold.co/600x400/22C55E/FFFFFF?text=French",
    },
    {
      id: 18,
      category: "education",
      subcategory: "online-courses",
      title: "Digital Marketing Online Course",
      provider: "EduTech Academy",
      pricePerTask: 25000,
      pricePerHour: 5000,
      rating: 4.7,
      reviews: 90,
      deliveries: 80,
      languages: ["English"],
      location: "Online",
      availability: "Available Now",
      avgDeliveryTime: 0, // Instant access
      image: "https://placehold.co/600x400/3B82F6/FFFFFF?text=Online+Course",
    },
  ],
};
