
export const categoriesData = [
  {
    label: "Technology & Digital Services",
    value: "technology",
    subcategories: [
      "Web Development",
      "Mobile App Development",
      "UI/UX Design",
      "Graphic Design",
      "Content Writing",
      "Copywriting",
      "SEO Optimization",
      "Digital Marketing",
      "Social Media Management",
      "Data Analysis",
      "Project Management",
      "E-commerce Development",
      "App Development",
      "IT Support",
      "Cybersecurity",
      "Cloud Engineering",
      "DevOps Engineering",
      "Database Administration",
      "System Administration",
      "Network Engineering",
      "QA & Testing",
    ],
  },
  {
    label: "Automotive Services",
    value: "automotive",
    subcategories: [
      "Auto Repair & Maintenance",
      "Diagnostics & Engine Services",
      "Brake & Transmission Services",
      "Tire Alignment",
      "Battery Services",
      "Car Detailing & Washing",
      "Body Repair & Paint",
      "Glass Replacement",
      "Oil Change & Lubrication",
      "Roadside Assistance",
      "Fleet Management",
      "Hybrid & EV Services",
      "Performance Tuning",
      "Auto Parts Supply",
      "Vehicle Customization",
      "Motorcycle Repair",
      "Heavy Equipment Repair",
    ],
  },
  {
    label: "Creative",
    value: "creative",
    subcategories: [
      "Visual Arts (Drawing, Painting, Sculpture)",
      "Artisanal Craft (Beading, Pottery, Woodwork)",
      "Handmade Products",
      "Installation Art",
      "Fashion Illustration",
      "Creative Direction",
      "Gallery Setup & Curation",
      "Art Restoration",
      "Calligraphy",
      "Branding & Identity Design",
      "Book Cover Design",
    ],
  },
  {
    label: "Food & Catering",
    value: "food_catering",
    subcategories: [
      "Event Catering",
      "Traditional Cuisine",
      "Baking & Pastries",
      "Cake Decoration",
      "Snack Production",
      "Food Delivery",
      "Food Packaging",
      "Private Chef Services",
    ],
  },
  {
    label: "Events & Entertainment",
    value: "events_entertainment",
    subcategories: [
      "Event Planning",
      "MC & Hosting",
      "DJ Services",
      "Live Band Performance",
      "Wedding Coordination",
      "Traditional Ceremonies",
      "Cultural Entertainment",
      "Event Decoration",
      "Stage & Lighting Setup",
    ],
  },
  {
    label: "Home Services",
    value: "home_services",
    subcategories: [
      "Plumbing",
      "Electrical Work",
      "Carpentry",
      "Painting Services",
      "HVAC Installation & Repair",
      "Pest Control",
      "Interior Design",
      "House Cleaning",
      "Furniture Making",
      "Upholstery",
      "Landscaping",
      "Roofing",
      "Gardening",
    ],
  },
  {
    label: "Professional Services",
    value: "professional_services",
    subcategories: [
      "Legal Services",
      "Accounting & Bookkeeping",
      "Business Consulting",
      "Real Estate Services",
      "Insurance Advisory",
      "Financial Planning",
      "Translation Services",
      "Educational Consulting",
      "Business Mentorship",
      "Proposal Writing",
    ],
  },
  {
    label: "Agriculture & Food Processing",
    value: "agriculture",
    subcategories: [
      "Farm Produce Supply",
      "Organic Farming",
      "Food Processing",
      "Livestock Management",
      "Agro-tech Services",
      "Agricultural Consultancy",
    ],
  },
  {
    label: "Fashion & Beauty",
    value: "fashion_beauty",
    subcategories: [
      "Fashion Design",
      "Tailoring Services",
      "Custom Attire",
      "Traditional Clothing",
      "Aso Ebi Coordination",
      "Wedding Attire",
      "Ankara Designs",
      "Clothing Alterations",
      "Jewelry Making",
      "Beadwork & Embellishment",
      "Makeup Artistry",
      "Hair Styling",
      "Skincare Consultation",
      "Beauty Therapy",
      "Nail Services",
      "Spa Services",
      "Personal Grooming",
      "Barbering",
    ],
  },
  {
    label: "Transportation & Logistics",
    value: "transportation",
    subcategories: [
      "Delivery Services",
      "Moving Services",
      "Logistics Coordination",
      "Supply Chain Management",
      "Driver Services",
      "Car Rentals",
      "Truck/Van Leasing",
      "Dispatch Services",
    ],
  },
  {
    label: "Security Services",
    value: "security",
    subcategories: [
      "Private Security",
      "Event Security",
      "Personal Bodyguards",
      "Surveillance System Setup",
      "Property Security",
      "Security Consultancy",
    ],
  },
  {
    label: "Media & Production",
    value: "media_production",
    subcategories: [
      "Photography",
      "Videography",
      "Video Editing",
      "Animation",
      "Voice Over",
      "Music Production",
      "Sound Editing",
      "Podcast Production",
      "Commercial Production",
      "Studio Management",
    ],
  },
  {
    label: "Education & Training",
    value: "education_training",
    subcategories: [
      "Private Tutoring",
      "Exam Prep (WAEC, JAMB, SAT, IELTS)",
      "Adult Education",
      "Online Course Creation",
      "Skill Development Coaching",
      "Professional Certifications",
      "Art & Music Classes",
      "Language Lessons",
      "Tech Training",
    ],
  },
  {
    label: "Health & Wellness",
    value: "health_wellness",
    subcategories: [
      "Personal Training",
      "Nutrition Consulting",
      "Massage Therapy",
      "Mental Health Services",
      "Yoga Instruction",
      "Physiotherapy",
      "Traditional Medicine",
      "Herbal Healing",
    ],
  },
  {
    label: "Repair & Maintenance",
    value: "repair_maintenance",
    subcategories: [
      "Phone Repair",
      "Computer Repair",
      "Appliance Repair",
      "Electronics Repair",
      "Furniture Repair",
      "Generator/Inverter Repair",
      "Camera & Lens Repair",
    ],
  },
];
