export const requestsData = {
    design: [
      {
        id: "req-1",
        title: "Logo design for fintech startup",
        category: "design",
        service: "Logo Design",
        description: "We need a clean, modern logo for a new fintech app targeting Gen Z users.",
        specification: "Flat style, 3 color options, scalable vector",
        budget: 200,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-15",
        location: "",
        requester: { id: "user-11", name: "Alex M.", rating: 4.7, totalRequests: 3 },
      },
      {
        id: "req-2",
        title: "UI redesign for SaaS landing page",
        category: "design",
        service: "UI/UX Design",
        description: "Redesign our SaaS landing page for better conversions.",
        specification: "Figma preferred, responsive layouts",
        budget: 500,
        paymentType: "milestone",
        engagementType: "remote",
        deadline: "2025-09-25",
        location: "",
        requester: { id: "user-14", name: "Sophie K.", rating: 4.9, totalRequests: 7 },
      },
      {
        id: "req-3",
        title: "Business card & stationery design",
        category: "design",
        service: "Branding",
        description: "Looking for sleek business card + letterhead design for law firm.",
        specification: "Minimalist, corporate feel",
        budget: 120,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-05",
        location: "",
        requester: { id: "user-22", name: "David P.", rating: 4.6, totalRequests: 2 },
      },
        {
        id: "req-89",
        title: "Infographic design for annual report",
        category: "design",
        service: "Infographic Design",
        description: "Create an engaging infographic summarizing our annual performance.",
        specification: "Data visualization, branded colors",
        budget: 300,
        paymentType: "milestone",
        engagementType: "remote",
        deadline: "2025-10-01",
        location: "",
        requester: { id: "user-30", name: "Olivia T.", rating: 4.8, totalRequests: 5 },
        },

    ],
  
    development: [
      {
        id: "req-4",
        title: "React Native app for food delivery",
        category: "development",
        service: "Mobile App Development",
        description: "Need a cross-platform app with real-time order tracking and payments.",
        specification: "React Native + Firebase backend",
        budget: 3000,
        paymentType: "milestone",
        engagementType: "hybrid",
        deadline: "2025-10-10",
        location: "New York, USA",
        requester: { id: "user-21", name: "Michael B.", rating: 4.5, totalRequests: 5 },
      },
      {
        id: "req-5",
        title: "E-commerce website with Shopify",
        category: "development",
        service: "Web Development",
        description: "Build an online store for handmade crafts with Shopify integration.",
        specification: "Payment gateway + product upload setup",
        budget: 1500,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-28",
        location: "",
        requester: { id: "user-33", name: "Hannah L.", rating: 4.9, totalRequests: 9 },
      },
      {
        id: "req-6",
        title: "Custom API for logistics tracking",
        category: "development",
        service: "Backend Development",
        description: "We need a secure REST API to handle shipment tracking and notifications.",
        specification: "Node.js + PostgreSQL",
        budget: 2000,
        paymentType: "milestone",
        engagementType: "onsite",
        deadline: "2025-11-01",
        location: "Berlin, Germany",
        requester: { id: "user-40", name: "Jonas S.", rating: 4.8, totalRequests: 4 },
      },
    ],
  
    writing: [
      {
        id: "req-7",
        title: "SEO blog posts for travel website",
        category: "writing",
        service: "Content Writing",
        description: "Looking for 10 blog posts (1000 words each) optimized for SEO.",
        specification: "Keyword research + SEO meta",
        budget: 800,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-30",
        location: "",
        requester: { id: "user-32", name: "Emma R.", rating: 4.8, totalRequests: 12 },
      },
      {
        id: "req-8",
        title: "Product descriptions for e-commerce site",
        category: "writing",
        service: "Copywriting",
        description: "Need 50 product descriptions for fashion store, 100–150 words each.",
        specification: "Engaging tone, SEO-friendly",
        budget: 400,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-18",
        location: "",
        requester: { id: "user-27", name: "Liam C.", rating: 4.4, totalRequests: 6 },
      },
      {
        id: "req-9",
        title: "Technical documentation for SaaS app",
        category: "writing",
        service: "Technical Writing",
        description: "Prepare onboarding docs and API reference for a SaaS project management app.",
        specification: "Markdown format, developer-focused",
        budget: 1000,
        paymentType: "milestone",
        engagementType: "remote",
        deadline: "2025-10-05",
        location: "",
        requester: { id: "user-45", name: "Nina G.", rating: 4.7, totalRequests: 8 },
      },
      {
        id: "req-10",
        title: "Ghostwriter for self-help book",
        category: "writing",
        service: "Ghostwriting",
        description: "Seeking an experienced writer to help draft a 50,000-word self-help book.",
        specification: "Weekly check-ins + revisions included",
        budget: 5000,
        paymentType: "milestone",
        engagementType: "remote",
        deadline: "2025-12-01",
        location: "",
        requester: { id: "user-55", name: "Sarah W.", rating: 4.9, totalRequests: 3 },
      },
      {
        id: "req-11",
        title: "Newsletter copy for tech startup",
        category: "writing",
        service: "Email Marketing",
        description: "Create engaging monthly newsletters for our tech audience.",
        specification: "2 newsletters per month, 500 words each",
        budget: 600,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-22",
        location: "",
        requester: { id: "user-65", name: "Tom H.", rating: 4.6, totalRequests: 1 },
      }
    ],
  
    marketing: [
      {
        id: "req-1899",
        title: "Facebook Ads campaign for fashion brand",
        category: "marketing",
        service: "Digital Marketing",
        description: "Run a 4-week FB ads campaign targeting 18–30 year olds in the US.",
        specification: "Ad creatives + reporting included",
        budget: 1200,
        paymentType: "milestone",
        engagementType: "remote",
        deadline: "2025-09-20",
        location: "",
        requester: { id: "user-50", name: "Rachel P.", rating: 4.9, totalRequests: 10 },
      },
      {
        id: "req-111",
        title: "Instagram influencer outreach",
        category: "marketing",
        service: "Social Media Marketing",
        description: "Looking for someone to find and contact fashion influencers.",
        specification: "List of 50 influencers with contact details",
        budget: 300,
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-12",
        location: "",
        requester: { id: "user-60", name: "James T.", rating: 4.3, totalRequests: 2 },
      },
        {
            id: "req-12",
            title: "SEO optimization for e-commerce site",
            category: "marketing",
            service: "SEO Services",
            description: "Improve our site’s SEO to rank higher for key product terms.",
            specification: "On-page + off-page SEO, 3-month engagement",
            budget: 1500,
            paymentType: "milestone",
            engagementType: "remote",
            deadline: "2025-10-15",
            location: "",
            requester: { id: "user-70", name: "Chris L.", rating: 4.8, totalRequests: 4 },
        },
        {   
        id: "req-13",
        title: "Email marketing campaign for product launch",
        category: "marketing",
        service: "Email Marketing",
        description: "Create and execute an email campaign for our new product launch.",
        specification: "3 emails + performance tracking",
        budget: 800,    
        paymentType: "project",
        engagementType: "remote",
        deadline: "2025-09-30",
        location: "",
        requester: { id: "user-75", name: "Laura S.", rating: 4.6, totalRequests: 3 },
        },
    ],
  };
  